### ISSUE TITLE
Merkle handling in PagedDb

### ISSUE THREAD

**Issue by Scooletz** [NethermindEth/Paprika#122]
Amend `PageDb` component so that it support Merkle construct. 

- [x] revisit existing maps (`NibbleBasedMap` and `HashingMap`) to see whether they fit the nature of Merkle, that can have keys and values pretty small, when comparing with others #131
- [x] leave some allowance on each internal Page to keep the MPT. Calculate how much memory will be needed and get it from the in-page cache component. This will limit the memory a bit, but will fix a blow up on truncating the path. #134
- [x] allow applying deletes (set operation with value of `Span<byte>.Empty`) and propagate it in the tree #138 
- [x] Massive Storage Tree should search for `Merkle` keys as well, so that the Merkle information about the storage is also extracted #138 
- [x] apply #118 by allowing the root of MPT be held in the first `DataPage`

Additional notes, covered by the points above. Keys are much shorter than other keys used in the `PagedDb`.  As `PagedDb` is path based, it uses full addresses of accounts and account+storage for storage. As it truncates one nibble per level of the page tree, it requires to leave some space for Merkle values as its keys will be much shorter, for example for the root, they will be of length of 0.

**Comment by Scooletz** [comment]
This has been addressed.
